language: rust
rust:
  - nightly

before_script: |
  rustup component add rustfmt-preview
script: |
  cargo fmt -- --write-mode=diff &&
  cargo build --verbose &&
  cargo test  --verbose
cache: cargo
